name: PublicApi
targets:
  PublicApi:
    type: framework
    platform: iOS
    deploymentTarget: "9.0"
    sources: [PublicApi]
    info:
      path: ./Info.plist
      version: 53.1.0
    settings:
      APPLICATION_EXTENSION_API_ONLY: true
    scheme: {}
    dependencies:
    - carthage: AnyCodable
