//
// AddAudienceScheduleToAudienceAlphaOutput.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Defines an Create Audience Schedule Output. */
public struct AddAudienceScheduleToAudienceAlphaOutput: Codable, JSONEncodable, Hashable {

    public var audienceSchedule: AudienceSchedule

    public init(audienceSchedule: AudienceSchedule) {
        self.audienceSchedule = audienceSchedule
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case audienceSchedule
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(audienceSchedule, forKey: .audienceSchedule)
    }
}

