//
// AddDestinationToAudienceAlphaInput.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Input to Add a Destination into an Audience. */
public struct AddDestinationToAudienceAlphaInput: Codable, JSONEncodable, Hashable {

    /** Version Schema. */
    public var versionSchema: String
    /** The id of the Workspace the audience exists within. */
    public var workspaceId: String
    public var destination: Destination

    public init(versionSchema: String, workspaceId: String, destination: Destination) {
        self.versionSchema = versionSchema
        self.workspaceId = workspaceId
        self.destination = destination
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case versionSchema
        case workspaceId
        case destination
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(versionSchema, forKey: .versionSchema)
        try container.encode(workspaceId, forKey: .workspaceId)
        try container.encode(destination, forKey: .destination)
    }
}

