//
// AddDestinationToAudienceAlphaInput.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Input to Add a Destination into an Audience. */
public struct AddDestinationToAudienceAlphaInput: Codable, JSONEncodable, Hashable {

    public var destination: Destination
    /** Identifier sync configuration. Defines which external ids to sync and their selection strategies. Maximum 5 items allowed. If omitted, the default will be last email and last user_id, or all email and all user_id depending on the Destination. */
    public var idSyncConfiguration: [IDSyncConfigurationInput]?
    /** The settings that a Destination requires to create audiences on a third-party platform. These settings are Destination-specific. Use the List Supported Destinations from Audience endpoint to find the required connection settings. */
    public var connectionSettings: AnyCodable?

    public init(destination: Destination, idSyncConfiguration: [IDSyncConfigurationInput]? = nil, connectionSettings: AnyCodable? = nil) {
        self.destination = destination
        self.idSyncConfiguration = idSyncConfiguration
        self.connectionSettings = connectionSettings
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case destination
        case idSyncConfiguration
        case connectionSettings
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(destination, forKey: .destination)
        try container.encodeIfPresent(idSyncConfiguration, forKey: .idSyncConfiguration)
        try container.encodeIfPresent(connectionSettings, forKey: .connectionSettings)
    }
}

