//
// AddUsersToUserGroupV1Input.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Adds a list of users and invites to a user group. */
public struct AddUsersToUserGroupV1Input: Codable, JSONEncodable, Hashable {

    /** The email addresses of the users and invites to add. */
    public var emails: [String]

    public init(emails: [String]) {
        self.emails = emails
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case emails
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(emails, forKey: .emails)
    }
}

