//
// AudiencePreviewEntitiesResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Result membership object for an audience preview with &#x60;audienceType: USERS&#x60; or &#x60;audienceType: LINKED&#x60;. */
public struct AudiencePreviewEntitiesResult: Codable, JSONEncodable, Hashable {

    /** The entities associated with the profile. Will only have a value if the audience preview has `audienceType: LINKED` and entities are referenced in the audience preview's definition. */
    public var entities: JSON?

    public init(entities: JSON? = nil) {
        self.entities = entities
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case entities
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(entities, forKey: .entities)
    }
}

