//
// AudienceComputeCadence.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AudienceComputeCadence: Codable, JSONEncodable, Hashable {

    public enum ModelType: String, Codable, CaseIterable {
        case batch = "BATCH"
        case realtime = "REALTIME"
    }
    /** The cadence type on which the audience's membership is computed. If 'BATCH', the audience is computed on a periodic basis. If 'REALTIME', the audience is continously computed. */
    public var type: ModelType

    public init(type: ModelType) {
        self.type = type
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
    }
}

