//
// ConditionSplitState.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ConditionSplitState: Codable, JSONEncodable, Hashable {

    public enum ModelType: String, Codable, CaseIterable {
        case conditionSplit = "CONDITION_SPLIT"
    }
    public var type: ModelType
    public var transitions: [TransitionsInner1]
    public var key: Key

    public init(type: ModelType, transitions: [TransitionsInner1], key: Key) {
        self.type = type
        self.transitions = transitions
        self.key = key
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case transitions
        case key
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(transitions, forKey: .transitions)
        try container.encode(key, forKey: .key)
    }
}

