//
// CreateValidationInWarehouseV2Input.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Verifies a Warehouse connection using a Credential by attempting to connect to it. */
public struct CreateValidationInWarehouseV2Input: Codable, JSONEncodable, Hashable {

    /** The id of the Credential to validate the connection with. The Warehouse type is derived from this Credential. */
    public var credentialId: String
    /** Optional settings overrides to check, layered on top of the Credential's own settings. */
    public var settings: JSON?

    public init(credentialId: String, settings: JSON? = nil) {
        self.credentialId = credentialId
        self.settings = settings
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case credentialId
        case settings
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(credentialId, forKey: .credentialId)
        try container.encodeIfPresent(settings, forKey: .settings)
    }
}

