//
// CreateCredentialV1Output.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Returns the newly created Credential. */
public struct CreateCredentialV1Output: Codable, JSONEncodable, Hashable {

    public var credential: Credential

    public init(credential: Credential) {
        self.credential = credential
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case credential
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(credential, forKey: .credential)
    }
}

