//
// DeleteTransformationFunctionInstanceAlphaInput.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Delete a Transformation Function instance. */
public struct DeleteTransformationFunctionInstanceAlphaInput: Codable, JSONEncodable, Hashable {

    /** An identifier for this Function. */
    public var instanceId: String

    public init(instanceId: String) {
        self.instanceId = instanceId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case instanceId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(instanceId, forKey: .instanceId)
    }
}

