//
// DestinationSubscriptionConfiguration.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Destination Subscription Configuration. */
public struct DestinationSubscriptionConfiguration: Codable, JSONEncodable, Hashable {

    /** The id for the action that Segment should perform on the Destination. The action cannot be changed once the Activation exists. When updating, this field is still required, but supplying a different value has no effect. */
    public var actionId: String
    /** The action/mapping settings. */
    public var settings: JSON?

    public init(actionId: String, settings: JSON? = nil) {
        self.actionId = actionId
        self.settings = settings
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case actionId
        case settings
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(actionId, forKey: .actionId)
        try container.encodeIfPresent(settings, forKey: .settings)
    }
}

