//
// DestinationInput.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The Destination Input Object. */
public struct DestinationInput: Codable, JSONEncodable, Hashable {

    /** The Destination id. Use the List Destinations endpoint to look up available ids. */
    public var id: String
    /** The category of the Destination.  Possible values: destination, warehouse. */
    public var type: String

    public init(id: String, type: String) {
        self.id = id
        self.type = type
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case type
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(type, forKey: .type)
    }
}

