//
// EntityDetails.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Entity details. */
public struct EntityDetails: Codable, JSONEncodable, Hashable {

    /** The entity primary key value. */
    public var id: String
    /** The entity primary key column name. */
    public var idProperty: String
    /** The entity relationship slug. */
    public var relationshipSlug: String
    /** The entity properties. */
    public var properties: JSON?
    /** The related entities one level deeper into an entity branch. */
    public var entities: [String: AnyCodable]?

    public init(id: String, idProperty: String, relationshipSlug: String, properties: JSON? = nil, entities: [String: AnyCodable]? = nil) {
        self.id = id
        self.idProperty = idProperty
        self.relationshipSlug = relationshipSlug
        self.properties = properties
        self.entities = entities
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case idProperty
        case relationshipSlug
        case properties
        case entities
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(idProperty, forKey: .idProperty)
        try container.encode(relationshipSlug, forKey: .relationshipSlug)
        try container.encodeIfPresent(properties, forKey: .properties)
        try container.encodeIfPresent(entities, forKey: .entities)
    }
}

