//
// EventEntryState.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct EventEntryState: Codable, JSONEncodable, Hashable {

    public enum ModelType: String, Codable, CaseIterable {
        case eventEntry = "EVENT_ENTRY"
    }
    public var type: ModelType
    public var condition: String
    public var transitions: [Transitions]
    public var key: Key

    public init(type: ModelType, condition: String, transitions: [Transitions], key: Key) {
        self.type = type
        self.condition = condition
        self.transitions = transitions
        self.key = key
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case condition
        case transitions
        case key
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(condition, forKey: .condition)
        try container.encode(transitions, forKey: .transitions)
        try container.encode(key, forKey: .key)
    }
}

