//
// ExitState.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ExitState: Codable, JSONEncodable, Hashable {

    public enum ModelType: String, Codable, CaseIterable {
        case exit = "EXIT"
    }
    public var type: ModelType
    public var key: Key

    public init(type: ModelType, key: Key) {
        self.type = type
        self.key = key
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case key
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(key, forKey: .key)
    }
}

