//
// FQLDefinedPropertyV1.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct FQLDefinedPropertyV1: Codable, JSONEncodable, Hashable {

    /** The FQL expression used to compute the property. */
    public var fql: String
    /** The new property name. */
    public var propertyName: String

    public init(fql: String, propertyName: String) {
        self.fql = fql
        self.propertyName = propertyName
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case fql
        case propertyName
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(fql, forKey: .fql)
        try container.encode(propertyName, forKey: .propertyName)
    }
}

