//
// GetDailyWorkspaceAPICallsUsageV1Output.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Returns a list of daily aggregations of Workspace MTU counts. */
public struct GetDailyWorkspaceAPICallsUsageV1Output: Codable, JSONEncodable, Hashable {

    /** The list of daily Workspace API calls count aggregates. */
    public var dailyWorkspaceAPICallsUsage: [APICallSnapshotV1]
    public var pagination: Pagination3

    public init(dailyWorkspaceAPICallsUsage: [APICallSnapshotV1], pagination: Pagination3) {
        self.dailyWorkspaceAPICallsUsage = dailyWorkspaceAPICallsUsage
        self.pagination = pagination
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case dailyWorkspaceAPICallsUsage
        case pagination
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(dailyWorkspaceAPICallsUsage, forKey: .dailyWorkspaceAPICallsUsage)
        try container.encode(pagination, forKey: .pagination)
    }
}

