//
// GetJourneyAnalyticsAlphaOutput.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Get journey analytics input. */
public struct GetJourneyAnalyticsAlphaOutput: Codable, JSONEncodable, Hashable {

    public var journeyAnalytics: JourneyAnalytics

    public init(journeyAnalytics: JourneyAnalytics) {
        self.journeyAnalytics = journeyAnalytics
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case journeyAnalytics
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(journeyAnalytics, forKey: .journeyAnalytics)
    }
}

