//
// GetSourceV1Output.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Returns a Source. */
public struct GetSourceV1Output: Codable, JSONEncodable, Hashable {

    public var source: Source5
    /** The id of the Tracking Plan connected to the Source. */
    public var trackingPlanId: String?

    public init(source: Source5, trackingPlanId: String?) {
        self.source = source
        self.trackingPlanId = trackingPlanId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case source
        case trackingPlanId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(source, forKey: .source)
        try container.encode(trackingPlanId, forKey: .trackingPlanId)
    }
}

