//
// GetTrackingPlanV1Output.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Gets a single Tracking Plan. */
public struct GetTrackingPlanV1Output: Codable, JSONEncodable, Hashable {

    public var trackingPlan: TrackingPlan

    public init(trackingPlan: TrackingPlan) {
        self.trackingPlan = trackingPlan
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case trackingPlan
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(trackingPlan, forKey: .trackingPlan)
    }
}

