//
// GetUserGroupV1Output.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Returns a user group with the given id. */
public struct GetUserGroupV1Output: Codable, JSONEncodable, Hashable {

    public var userGroup: UserGroup2

    public init(userGroup: UserGroup2) {
        self.userGroup = userGroup
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case userGroup
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(userGroup, forKey: .userGroup)
    }
}

