//
// GetWarehouseMetadataV1Output.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Returns a Warehouse catalog item looked up by id. */
public struct GetWarehouseMetadataV1Output: Codable, JSONEncodable, Hashable {

    public var warehouseMetadata: WarehouseMetadata

    public init(warehouseMetadata: WarehouseMetadata) {
        self.warehouseMetadata = warehouseMetadata
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case warehouseMetadata
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(warehouseMetadata, forKey: .warehouseMetadata)
    }
}

