//
// IDSyncConfigurationInput.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The identifier sync configuration input. */
public struct IDSyncConfigurationInput: Codable, JSONEncodable, Hashable {

    /** The external id to sync, for example \"user_id\" or \"email\". */
    public var externalId: String
    /** The strategy for syncing this identifier. Valid values: \"first\", \"last\", \"all\". */
    public var strategy: String

    public init(externalId: String, strategy: String) {
        self.externalId = externalId
        self.strategy = strategy
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case externalId
        case strategy
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(externalId, forKey: .externalId)
        try container.encode(strategy, forKey: .strategy)
    }
}

