//
// Journey.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The created journey summary. */
public struct Journey: Codable, JSONEncodable, Hashable {

    public enum ExecutionState: String, Codable, CaseIterable {
        case draft = "DRAFT"
        case published = "PUBLISHED"
    }
    /** Journey id. */
    public var id: String
    /** Space id for the journey. */
    public var spaceId: String
    /** Display name. */
    public var name: String
    /** Execution state of the journey. */
    public var executionState: ExecutionState
    /** ISO timestamp. */
    public var createdAt: String
    /** ISO timestamp. */
    public var updatedAt: String

    public init(id: String, spaceId: String, name: String, executionState: ExecutionState, createdAt: String, updatedAt: String) {
        self.id = id
        self.spaceId = spaceId
        self.name = name
        self.executionState = executionState
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case spaceId
        case name
        case executionState
        case createdAt
        case updatedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(spaceId, forKey: .spaceId)
        try container.encode(name, forKey: .name)
        try container.encode(executionState, forKey: .executionState)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(updatedAt, forKey: .updatedAt)
    }
}

