//
// ListDestinationsFromAudienceAlphaOutput.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Output to List all Destinations from an Audience. */
public struct ListDestinationsFromAudienceAlphaOutput: Codable, JSONEncodable, Hashable {

    /** A list of connection results. */
    public var connections: [SimpleDestination]
    public var pagination: Pagination1?

    public init(connections: [SimpleDestination], pagination: Pagination1? = nil) {
        self.connections = connections
        self.pagination = pagination
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case connections
        case pagination
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(connections, forKey: .connections)
        try container.encodeIfPresent(pagination, forKey: .pagination)
    }
}

