//
// ListPropertiesFromEntityAlphaOutput.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Response for the listPropertiesFromEntity endpoint. */
public struct ListPropertiesFromEntityAlphaOutput: Codable, JSONEncodable, Hashable {

    /** List of properties for the entity. */
    public var entityProperties: [EntityPropertyAlpha]
    public var pagination: Pagination8

    public init(entityProperties: [EntityPropertyAlpha], pagination: Pagination8) {
        self.entityProperties = entityProperties
        self.pagination = pagination
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case entityProperties
        case pagination
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(entityProperties, forKey: .entityProperties)
        try container.encode(pagination, forKey: .pagination)
    }
}

