//
// ListInvitesFromUserGroupV1Output.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Returns the emails of invitees to a user group with the given group id. */
public struct ListInvitesFromUserGroupV1Output: Codable, JSONEncodable, Hashable {

    /** The emails of the invitees to the user group. */
    public var emails: [String]
    public var pagination: Pagination3

    public init(emails: [String], pagination: Pagination3) {
        self.emails = emails
        self.pagination = pagination
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case emails
        case pagination
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(emails, forKey: .emails)
        try container.encode(pagination, forKey: .pagination)
    }
}

