//
// ListSyncsFromWarehouseAndSourceV1Output.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Returns a list that contains the most recent syncs for a Warehouse-source pair, filtered and constrained by a given set of pagination parameters. */
public struct ListSyncsFromWarehouseAndSourceV1Output: Codable, JSONEncodable, Hashable {

    /** A list that contains the latest syncs for the specified Warehouse-source pair. */
    public var reports: [SyncV1]
    public var pagination: Pagination2

    public init(reports: [SyncV1], pagination: Pagination2) {
        self.reports = reports
        self.pagination = pagination
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case reports
        case pagination
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(reports, forKey: .reports)
        try container.encode(pagination, forKey: .pagination)
    }
}

