//
// ListRegulationsFromSourceV1Output.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Output of all Source-scoped regulations. */
public struct ListRegulationsFromSourceV1Output: Codable, JSONEncodable, Hashable {

    /** List of Workspace-scoped regulations with statuses. */
    public var regulations: [RegulationListEntryV1]

    public init(regulations: [RegulationListEntryV1]) {
        self.regulations = regulations
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case regulations
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(regulations, forKey: .regulations)
    }
}

