//
// ListPropertiesFromEventAlphaOutput.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Response for the listPropertiesFromEvent endpoint. */
public struct ListPropertiesFromEventAlphaOutput: Codable, JSONEncodable, Hashable {

    /** List of properties for the event. */
    public var eventProperties: [EventPropertyAlpha]
    public var pagination: Pagination7

    public init(eventProperties: [EventPropertyAlpha], pagination: Pagination7) {
        self.eventProperties = eventProperties
        self.pagination = pagination
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case eventProperties
        case pagination
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(eventProperties, forKey: .eventProperties)
        try container.encode(pagination, forKey: .pagination)
    }
}

