//
// ListFunctionsV1Output.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Lists Functions in a Workspace. */
public struct ListFunctionsV1Output: Codable, JSONEncodable, Hashable {

    /** An array of Functions. */
    public var functions: [ListFunctionItemV1]
    public var pagination: Pagination1

    public init(functions: [ListFunctionItemV1], pagination: Pagination1) {
        self.functions = functions
        self.pagination = pagination
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case functions
        case pagination
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(functions, forKey: .functions)
        try container.encode(pagination, forKey: .pagination)
    }
}

