//
// ListSchemaSettingsInSourceV1Output.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Returns a list of settings for the Source. */
public struct ListSchemaSettingsInSourceV1Output: Codable, JSONEncodable, Hashable {

    /** Source id.  Config API note: analogous to `parent` and `name`. */
    public var sourceId: String
    public var settings: Settings

    public init(sourceId: String, settings: Settings) {
        self.sourceId = sourceId
        self.settings = settings
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case sourceId
        case settings
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(sourceId, forKey: .sourceId)
        try container.encode(settings, forKey: .settings)
    }
}

