//
// ListAuditEventsV1Output.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Returns a list of Audit Trail events for the current Workspace. */
public struct ListAuditEventsV1Output: Codable, JSONEncodable, Hashable {

    /** Audit trail events for the current Workspace. */
    public var events: [AuditEventV1]
    public var pagination: Pagination2?

    public init(events: [AuditEventV1], pagination: Pagination2? = nil) {
        self.events = events
        self.pagination = pagination
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case events
        case pagination
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(events, forKey: .events)
        try container.encodeIfPresent(pagination, forKey: .pagination)
    }
}

