//
// ListWorkspaceRegulationsV1Output.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Output of all Workspace-scoped regulations in a given Workspace. */
public struct ListWorkspaceRegulationsV1Output: Codable, JSONEncodable, Hashable {

    /** List of Workspace-scoped regulations with statuses. */
    public var regulations: [RegulationListEntryV1]
    public var pagination: Pagination3

    public init(regulations: [RegulationListEntryV1], pagination: Pagination3) {
        self.regulations = regulations
        self.pagination = pagination
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case regulations
        case pagination
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(regulations, forKey: .regulations)
        try container.encode(pagination, forKey: .pagination)
    }
}

