//
// ListAudienceSchedulesFromSpaceAndAudienceAlphaOutput.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Output for list audience schedules. */
public struct ListAudienceSchedulesFromSpaceAndAudienceAlphaOutput: Codable, JSONEncodable, Hashable {

    /** A list of audience schedules. */
    public var audienceSchedules: [AudienceSchedule]

    public init(audienceSchedules: [AudienceSchedule]) {
        self.audienceSchedules = audienceSchedules
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case audienceSchedules
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(audienceSchedules, forKey: .audienceSchedules)
    }
}

