//
// ListCredentialConsumersV1Output.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Returns the Warehouses and Sources that consume a Credential, each paginated independently. */
public struct ListCredentialConsumersV1Output: Codable, JSONEncodable, Hashable {

    /** The Warehouses that use this Credential. */
    public var warehouses: [WarehouseV1]
    public var warehousesPagination: WarehousesPagination
    /** The Sources that use this Credential. */
    public var sources: [SourceV1]
    public var sourcesPagination: SourcesPagination

    public init(warehouses: [WarehouseV1], warehousesPagination: WarehousesPagination, sources: [SourceV1], sourcesPagination: SourcesPagination) {
        self.warehouses = warehouses
        self.warehousesPagination = warehousesPagination
        self.sources = sources
        self.sourcesPagination = sourcesPagination
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case warehouses
        case warehousesPagination
        case sources
        case sourcesPagination
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(warehouses, forKey: .warehouses)
        try container.encode(warehousesPagination, forKey: .warehousesPagination)
        try container.encode(sources, forKey: .sources)
        try container.encode(sourcesPagination, forKey: .sourcesPagination)
    }
}

