//
// ListProfilesWarehouseInSpaceAlphaOutput.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Returns all Profiles Warehouse based on spaceID and pagination. */
public struct ListProfilesWarehouseInSpaceAlphaOutput: Codable, JSONEncodable, Hashable {

    /** A list of Warehouses that belong to the Workspace. */
    public var profilesWarehouses: [ProfilesWarehouseAlpha]
    public var pagination: Pagination1?

    public init(profilesWarehouses: [ProfilesWarehouseAlpha], pagination: Pagination1? = nil) {
        self.profilesWarehouses = profilesWarehouses
        self.pagination = pagination
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case profilesWarehouses
        case pagination
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(profilesWarehouses, forKey: .profilesWarehouses)
        try container.encodeIfPresent(pagination, forKey: .pagination)
    }
}

