//
// Metadata1.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The metadata for the Warehouse. */
public struct Metadata1: Codable, JSONEncodable, Hashable {

    /** The id of this object. */
    public var id: String
    /** The name of this object. */
    public var name: String
    /** A human-readable, unique identifier for object. */
    public var slug: String
    /** A description, in English, of this object. */
    public var description: String
    public var logos: Logos2
    /** The Integration options for this object. */
    public var options: [IntegrationOptionBeta]

    public init(id: String, name: String, slug: String, description: String, logos: Logos2, options: [IntegrationOptionBeta]) {
        self.id = id
        self.name = name
        self.slug = slug
        self.description = description
        self.logos = logos
        self.options = options
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case slug
        case description
        case logos
        case options
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encode(slug, forKey: .slug)
        try container.encode(description, forKey: .description)
        try container.encode(logos, forKey: .logos)
        try container.encode(options, forKey: .options)
    }
}

