//
// Options.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Represents the options of Including Anonymous users and Historical Data. */
public struct Options: Codable, JSONEncodable, Hashable {

    /** Determines whether data prior to the audience being created is included when determining audience membership. Note that including historical data may be needed in order to properly handle the definition specified. In these cases, Segment will automatically handle including historical data and the response will return the includeHistoricalData parameter as true. */
    public var includeHistoricalData: Bool?
    /** The set of profile external identifiers being used to determine audience membership. Profiles will only be considered for audience membership if the profile has at least one external id whose key matches a value in this set. */
    public var filterByExternalIds: [String]?
    /** If specified, the value of this field indicates the number of days, specified from the date the audience was created, that event data will be included from when determining audience membership. If unspecified, defer to the value of `includeHistoricalData` to determine whether historical data is either entirely included or entirely excluded when determining audience membership. */
    public var backfillEventDataDays: Double?

    public init(includeHistoricalData: Bool? = nil, filterByExternalIds: [String]? = nil, backfillEventDataDays: Double? = nil) {
        self.includeHistoricalData = includeHistoricalData
        self.filterByExternalIds = filterByExternalIds
        self.backfillEventDataDays = backfillEventDataDays
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case includeHistoricalData
        case filterByExternalIds
        case backfillEventDataDays
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(includeHistoricalData, forKey: .includeHistoricalData)
        try container.encodeIfPresent(filterByExternalIds, forKey: .filterByExternalIds)
        try container.encodeIfPresent(backfillEventDataDays, forKey: .backfillEventDataDays)
    }
}

