//
// Personalization.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Configuration settings for the event emitter to be created. */
public struct Personalization: Codable, JSONEncodable, Hashable {

    public var profile: Profile
    /** Entities V2 Object. */
    public var entities: [PersonalizationInputEntity]?

    public init(profile: Profile, entities: [PersonalizationInputEntity]? = nil) {
        self.profile = profile
        self.entities = entities
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case profile
        case entities
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(profile, forKey: .profile)
        try container.encodeIfPresent(entities, forKey: .entities)
    }
}

