//
// Personalization.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The data points used to enrich the event. Defines which profile traits and/or entity properties are included in the event sent to the Destination.  For Action Destinations, any traits or properties specified here must also be included in the destinationMapping to define which Destination fields should be populated. */
public struct Personalization: Codable, JSONEncodable, Hashable {

    public var profile: Profile
    /** Entities V2 Object. */
    public var entities: [PersonalizationInputEntity]?
    /** Sync entity property changes to the Destination. Only applicable if activationType is \"Audience Membership Changed\". */
    public var syncEntityPropertyChanges: Bool?

    public init(profile: Profile, entities: [PersonalizationInputEntity]? = nil, syncEntityPropertyChanges: Bool? = nil) {
        self.profile = profile
        self.entities = entities
        self.syncEntityPropertyChanges = syncEntityPropertyChanges
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case profile
        case entities
        case syncEntityPropertyChanges
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(profile, forKey: .profile)
        try container.encodeIfPresent(entities, forKey: .entities)
        try container.encodeIfPresent(syncEntityPropertyChanges, forKey: .syncEntityPropertyChanges)
    }
}

