//
// Personalization.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Configuration settings for the event emitter to be created. */
public struct Personalization: Codable, JSONEncodable, Hashable {

    public var profile: Profile
    /** Entities V2 Object. */
    public var entities: [PersonalizationInputEntity]?
    /** Sync entity property changes back to Segment. Only applicable if activationType is \"Audience Membership Changed\" and segmentEvent is \"identify\". */
    public var syncEntityPropertyChanges: Bool?

    public init(profile: Profile, entities: [PersonalizationInputEntity]? = nil, syncEntityPropertyChanges: Bool? = nil) {
        self.profile = profile
        self.entities = entities
        self.syncEntityPropertyChanges = syncEntityPropertyChanges
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case profile
        case entities
        case syncEntityPropertyChanges
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(profile, forKey: .profile)
        try container.encodeIfPresent(entities, forKey: .entities)
        try container.encodeIfPresent(syncEntityPropertyChanges, forKey: .syncEntityPropertyChanges)
    }
}

