//
// Personalization3.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Optional profile traits and Linked Audience entity properties to include in the export. Select profile traits with &#x60;profile.properties&#x60;, using physical Segment trait names. Select entity properties with &#x60;entities&#x60;, using physical Segment relationship names in &#x60;relationshipSlug&#x60; and physical entity-property names in &#x60;properties&#x60;. Entity personalization is initially supported only for Linked Audiences. CSV exports do not support &#x60;profile.mapping&#x60; or &#x60;syncEntityPropertyChanges&#x60;. Omit this field to preserve the default Audience CSV export behavior. Public API does not interpret template-friendly names or template languages. */
public struct Personalization3: Codable, JSONEncodable, Hashable {

    public var profile: Profile?
    /** The entities, and the properties of each entity, to include in the event sent to the Destination. Only applicable to Linked Audiences. Providing entities for a Classic audience returns a 400 error, as Classic audiences support profile properties only. */
    public var entities: [PersonalizationInputEntity]?
    /** Sync entity property changes to the Destination. Only applicable if activationType is \"Audience Membership Changed\". */
    public var syncEntityPropertyChanges: Bool?

    public init(profile: Profile? = nil, entities: [PersonalizationInputEntity]? = nil, syncEntityPropertyChanges: Bool? = nil) {
        self.profile = profile
        self.entities = entities
        self.syncEntityPropertyChanges = syncEntityPropertyChanges
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case profile
        case entities
        case syncEntityPropertyChanges
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(profile, forKey: .profile)
        try container.encodeIfPresent(entities, forKey: .entities)
        try container.encodeIfPresent(syncEntityPropertyChanges, forKey: .syncEntityPropertyChanges)
    }
}

