//
// PropertySelectionsConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PropertySelectionsConfig: Codable, JSONEncodable, Hashable {

    public var profile: [String]

    public init(profile: [String]) {
        self.profile = profile
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case profile
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(profile, forKey: .profile)
    }
}

