//
// PropertyRenameV1.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PropertyRenameV1: Codable, JSONEncodable, Hashable {

    /** The old name of the property. */
    public var oldName: String
    /** The new name to rename the property. */
    public var newName: String

    public init(oldName: String, newName: String) {
        self.oldName = oldName
        self.newName = newName
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case oldName
        case newName
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(oldName, forKey: .oldName)
        try container.encode(newName, forKey: .newName)
    }
}

