//
// RandomSplitBranch.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RandomSplitBranch: Codable, JSONEncodable, Hashable {

    public var percentage: Double
    public var next: String

    public init(percentage: Double, next: String) {
        self.percentage = percentage
        self.next = next
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case percentage
        case next
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(percentage, forKey: .percentage)
        try container.encode(next, forKey: .next)
    }
}

