//
// ReplaceLabelsInSourceAlphaInput.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Replaces all labels in a Source with a list of new labels. */
public struct ReplaceLabelsInSourceAlphaInput: Codable, JSONEncodable, Hashable {

    /** The list of labels to replace in the Source. */
    public var labels: [LabelAlpha]

    public init(labels: [LabelAlpha]) {
        self.labels = labels
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case labels
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(labels, forKey: .labels)
    }
}

