//
// ReplaceStepsForJourneyAlphaInput.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Replace steps for a journey input. */
public struct ReplaceStepsForJourneyAlphaInput: Codable, JSONEncodable, Hashable {

    /** The Initial state of the journey. */
    public var initialState: String
    /** States of the journey. */
    public var states: [JourneyState]

    public init(initialState: String, states: [JourneyState]) {
        self.initialState = initialState
        self.states = states
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case initialState
        case states
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(initialState, forKey: .initialState)
        try container.encode(states, forKey: .states)
    }
}

