//
// ReverseEtlDbtCloudScheduleConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Definition for a schedule triggered by dbt Cloud job events. */
public struct ReverseEtlDbtCloudScheduleConfig: Codable, JSONEncodable, Hashable {

    /** The dbt Cloud job used to trigger a sync for a Reverse ETL Connection. */
    public var jobId: String
    /** The dbt Cloud account where the job belongs to. */
    public var accountId: String

    public init(jobId: String, accountId: String) {
        self.jobId = jobId
        self.accountId = accountId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case jobId
        case accountId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(jobId, forKey: .jobId)
        try container.encode(accountId, forKey: .accountId)
    }
}

