//
// ReverseEtlCronScheduleConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ReverseEtlCronScheduleConfig: Codable, JSONEncodable, Hashable {

    /** 5 field cron string expression. The cron expression must be larger than 15 minutes. */
    public var spec: String
    /** Timezone respected by the cron string. Format must be in IANA Timezone Identifier. Example: 'America/Los_Angeles'. */
    public var timezone: String

    public init(spec: String, timezone: String) {
        self.spec = spec
        self.timezone = timezone
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case spec
        case timezone
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(spec, forKey: .spec)
        try container.encode(timezone, forKey: .timezone)
    }
}

