//
// SimpleDestination.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SimpleDestination: Codable, JSONEncodable, Hashable {

    /** The id of the Integration. */
    public var id: String
    /** The name of the Destination. */
    public var name: String?
    /** The Source of the Destination. */
    public var sourceId: String
    /** Whether the Integration is enabled or not. */
    public var enabled: Bool
    /** When the Integration connection was created. */
    public var createdAt: String
    /** When the Integration connection was last updated. */
    public var updatedAt: String
    /** The Destination settings. */
    public var settings: [String: AnyCodable]
    /** The Destination id. */
    public var destinationId: String
    public var metadata: Metadata?
    /** ID Sync configuration - array of external IDs with their strategies. */
    public var idSyncConfiguration: [IDSyncConfigurationInput]?
    /** The settings that a Destination requires to create audiences on a third-party platform. These settings are Destination-specific and thus are best defined as unknown. */
    public var connectionSettings: AnyCodable?

    public init(id: String, name: String? = nil, sourceId: String, enabled: Bool, createdAt: String, updatedAt: String, settings: [String: AnyCodable], destinationId: String, metadata: Metadata? = nil, idSyncConfiguration: [IDSyncConfigurationInput]? = nil, connectionSettings: AnyCodable? = nil) {
        self.id = id
        self.name = name
        self.sourceId = sourceId
        self.enabled = enabled
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.settings = settings
        self.destinationId = destinationId
        self.metadata = metadata
        self.idSyncConfiguration = idSyncConfiguration
        self.connectionSettings = connectionSettings
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case sourceId
        case enabled
        case createdAt
        case updatedAt
        case settings
        case destinationId
        case metadata
        case idSyncConfiguration
        case connectionSettings
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encode(sourceId, forKey: .sourceId)
        try container.encode(enabled, forKey: .enabled)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(updatedAt, forKey: .updatedAt)
        try container.encode(settings, forKey: .settings)
        try container.encode(destinationId, forKey: .destinationId)
        try container.encodeIfPresent(metadata, forKey: .metadata)
        try container.encodeIfPresent(idSyncConfiguration, forKey: .idSyncConfiguration)
        try container.encodeIfPresent(connectionSettings, forKey: .connectionSettings)
    }
}

