//
// SourceEventVolumeDatapointV1.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** SourceEventVolumeDatapoint represents an individual timestamp/event count pair corresponding to a window of time designated by the granularity. */
public struct SourceEventVolumeDatapointV1: Codable, JSONEncodable, Hashable {

    /** The timestamp that corresponds to the beginning of the window given by the requested granularity. */
    public var time: String
    /** The number of valid events Segment received in the given window, after the events completed the validation process. */
    public var count: Double

    public init(time: String, count: Double) {
        self.time = time
        self.count = count
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case time
        case count
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(time, forKey: .time)
        try container.encode(count, forKey: .count)
    }
}

