//
// SpaceWarehouseSchemaOverride.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Overrides the enabled or disabled state of the specified collection and / or properties within the schema. */
public struct SpaceWarehouseSchemaOverride: Codable, JSONEncodable, Hashable {

    /** The collection within the Source. */
    public var collection: String
    /** Represents the overridden enabled state for the listed collection and / or properties. */
    public var enabled: Bool
    /** A map that contains the properties within the collection to which the Warehouse should sync. */
    public var property: String?

    public init(collection: String, enabled: Bool, property: String? = nil) {
        self.collection = collection
        self.enabled = enabled
        self.property = property
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case collection
        case enabled
        case property
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(collection, forKey: .collection)
        try container.encode(enabled, forKey: .enabled)
        try container.encodeIfPresent(property, forKey: .property)
    }
}

