//
// TraitType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum TraitType: String, Codable, CaseIterable {
    case audience = "AUDIENCE"
    case computed = "COMPUTED"
    case custom = "CUSTOM"
    case sql = "SQL"
}
