//
// UpdateDestinationForAudienceAlphaOutput.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Output for updating a Destination for an Audience. */
public struct UpdateDestinationForAudienceAlphaOutput: Codable, JSONEncodable, Hashable {

    public var destination: Destination1
    /** The id sync configuration for the Destination - array of external ids with their strategies. */
    public var idSyncConfiguration: [IDSyncConfigurationInput]?
    /** The settings that a Destination requires to create audiences on a third-party platform. */
    public var connectionSettings: AnyCodable?

    public init(destination: Destination1, idSyncConfiguration: [IDSyncConfigurationInput]? = nil, connectionSettings: AnyCodable? = nil) {
        self.destination = destination
        self.idSyncConfiguration = idSyncConfiguration
        self.connectionSettings = connectionSettings
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case destination
        case idSyncConfiguration
        case connectionSettings
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(destination, forKey: .destination)
        try container.encodeIfPresent(idSyncConfiguration, forKey: .idSyncConfiguration)
        try container.encodeIfPresent(connectionSettings, forKey: .connectionSettings)
    }
}

