//
// UpdateStatusForJourneyAlphaInput.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Update journey status input. */
public struct UpdateStatusForJourneyAlphaInput: Codable, JSONEncodable, Hashable {

    public enum Action: String, Codable, CaseIterable {
        case archive = "ARCHIVE"
        case pauseEntry = "PAUSE_ENTRY"
        case publish = "PUBLISH"
    }
    /** The journey version. */
    public var version: Double
    /** The action to perform for the journey. */
    public var action: Action

    public init(version: Double, action: Action) {
        self.version = version
        self.action = action
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case version
        case action
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(version, forKey: .version)
        try container.encode(action, forKey: .action)
    }
}

