//
// UpdateTransformationFunctionInstanceAlphaOutput.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Returns the updated Transformation Function instance. */
public struct UpdateTransformationFunctionInstanceAlphaOutput: Codable, JSONEncodable, Hashable {

    public var transformationFunctionInstance: TransformationFunctionInstance1

    public init(transformationFunctionInstance: TransformationFunctionInstance1) {
        self.transformationFunctionInstance = transformationFunctionInstance
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case transformationFunctionInstance
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(transformationFunctionInstance, forKey: .transformationFunctionInstance)
    }
}

