//
// UpdateComputedTraitForSpaceAlphaOutput.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Computed Trait output for get and update. */
public struct UpdateComputedTraitForSpaceAlphaOutput: Codable, JSONEncodable, Hashable {

    public var computedTrait: ComputedTrait

    public init(computedTrait: ComputedTrait) {
        self.computedTrait = computedTrait
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case computedTrait
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(computedTrait, forKey: .computedTrait)
    }
}

