//
// UpdateActivationForAudienceAlphaInput.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Input to update an activation. */
public struct UpdateActivationForAudienceAlphaInput: Codable, JSONEncodable, Hashable {

    /** Determines whether an activation is enabled. */
    public var enabled: Bool?
    /** Activation name. For Warehouse Destinations, this is used as the table name. Omit this field to leave the name unchanged. An empty string is ignored rather than applied. */
    public var activationName: String?
    /** Optional human-readable label for the activation. Only supported for Warehouse Destinations. Send null to clear. When omitted, the activationName is used as the label. */
    public var displayName: String?
    public var personalization: Personalization1?
    public var destinationMapping: DestinationMapping1?
    /** Determines whether to perform a full resync after the update. If true, the entire audience is resent to the Destination using the updated configuration. If false, the update applies only to future syncs. */
    public var performResync: Bool?

    public init(enabled: Bool? = nil, activationName: String? = nil, displayName: String? = nil, personalization: Personalization1? = nil, destinationMapping: DestinationMapping1? = nil, performResync: Bool? = nil) {
        self.enabled = enabled
        self.activationName = activationName
        self.displayName = displayName
        self.personalization = personalization
        self.destinationMapping = destinationMapping
        self.performResync = performResync
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case enabled
        case activationName
        case displayName
        case personalization
        case destinationMapping
        case performResync
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(enabled, forKey: .enabled)
        try container.encodeIfPresent(activationName, forKey: .activationName)
        try container.encodeIfPresent(displayName, forKey: .displayName)
        try container.encodeIfPresent(personalization, forKey: .personalization)
        try container.encodeIfPresent(destinationMapping, forKey: .destinationMapping)
        try container.encodeIfPresent(performResync, forKey: .performResync)
    }
}

