//
// CreateDestinationV1Output.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Creates a new Destination. */
public struct CreateDestinationV1Output: Codable, JSONEncodable, Hashable {

    public var destination: Destination2

    public init(destination: Destination2) {
        self.destination = destination
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case destination
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(destination, forKey: .destination)
    }
}

