//
// GetWorkspaceV1Output.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Represents the output of loading the Workspace. */
public struct GetWorkspaceV1Output: Codable, JSONEncodable, Hashable {

    public var workspace: Workspace

    public init(workspace: Workspace) {
        self.workspace = workspace
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case workspace
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(workspace, forKey: .workspace)
    }
}

