//
// UserGroup3.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The updated user group. */
public struct UserGroup3: Codable, JSONEncodable, Hashable {

    /** The number of members in the user group. */
    public var memberCount: Double
    /** The permissions associated with the user group. */
    public var permissions: [PermissionV1]?
    /** The id of the user group. */
    public var id: String
    /** The name of the user group. */
    public var name: String

    public init(memberCount: Double, permissions: [PermissionV1]? = nil, id: String, name: String) {
        self.memberCount = memberCount
        self.permissions = permissions
        self.id = id
        self.name = name
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case memberCount
        case permissions
        case id
        case name
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(memberCount, forKey: .memberCount)
        try container.encodeIfPresent(permissions, forKey: .permissions)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
    }
}

