//
// CredentialsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class CredentialsAPI {

    /**
     Create Credential
     
     - parameter createCredentialV1Input: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func createCredential(createCredentialV1Input: CreateCredentialV1Input, apiResponseQueue: DispatchQueue = PublicApiAPI.apiResponseQueue, completion: @escaping ((_ data: CreateCredential201Response?, _ error: Error?) -> Void)) -> RequestTask {
        return createCredentialWithRequestBuilder(createCredentialV1Input: createCredentialV1Input).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Create Credential
     - POST /credentials
     - Creates a new Credential.
     - BASIC:
       - type: http
       - name: token
     - parameter createCredentialV1Input: (body)  
     - returns: RequestBuilder<CreateCredential201Response> 
     */
    open class func createCredentialWithRequestBuilder(createCredentialV1Input: CreateCredentialV1Input) -> RequestBuilder<CreateCredential201Response> {
        let localVariablePath = "/credentials"
        let localVariableURLString = PublicApiAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: createCredentialV1Input)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateCredential201Response>.Type = PublicApiAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }

    /**
     Update Credential
     
     - parameter credentialId: (path)  
     - parameter updateCredentialV1Input: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func updateCredential(credentialId: String, updateCredentialV1Input: UpdateCredentialV1Input, apiResponseQueue: DispatchQueue = PublicApiAPI.apiResponseQueue, completion: @escaping ((_ data: UpdateCredential200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return updateCredentialWithRequestBuilder(credentialId: credentialId, updateCredentialV1Input: updateCredentialV1Input).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Update Credential
     - PATCH /credentials/{credentialId}
     - Updates an existing Credential. All Warehouses using this Credential are affected immediately.
     - BASIC:
       - type: http
       - name: token
     - parameter credentialId: (path)  
     - parameter updateCredentialV1Input: (body)  
     - returns: RequestBuilder<UpdateCredential200Response> 
     */
    open class func updateCredentialWithRequestBuilder(credentialId: String, updateCredentialV1Input: UpdateCredentialV1Input) -> RequestBuilder<UpdateCredential200Response> {
        var localVariablePath = "/credentials/{credentialId}"
        let credentialIdPreEscape = "\(APIHelper.mapValueToPathItem(credentialId))"
        let credentialIdPostEscape = credentialIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{credentialId}", with: credentialIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = PublicApiAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: updateCredentialV1Input)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<UpdateCredential200Response>.Type = PublicApiAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PATCH", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }
}
