//
// JourneysAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class JourneysAPI {

    /**
     Create Journey
     
     - parameter spaceId: (path)  
     - parameter createJourneyAlphaInput: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func createJourney(spaceId: String, createJourneyAlphaInput: CreateJourneyAlphaInput, apiResponseQueue: DispatchQueue = PublicApiAPI.apiResponseQueue, completion: @escaping ((_ data: CreateJourney200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return createJourneyWithRequestBuilder(spaceId: spaceId, createJourneyAlphaInput: createJourneyAlphaInput).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Create Journey
     - POST /spaces/{spaceId}/journeys
     - Creates a Journey in the given Engage space. Accepts an XState journey definition and creates the journey in draft state.  • This endpoint is in **Alpha** testing.  Please submit any feedback by sending an email to friends@segment.com. 
     - BASIC:
       - type: http
       - name: token
     - parameter spaceId: (path)  
     - parameter createJourneyAlphaInput: (body)  
     - returns: RequestBuilder<CreateJourney200Response> 
     */
    open class func createJourneyWithRequestBuilder(spaceId: String, createJourneyAlphaInput: CreateJourneyAlphaInput) -> RequestBuilder<CreateJourney200Response> {
        var localVariablePath = "/spaces/{spaceId}/journeys"
        let spaceIdPreEscape = "\(APIHelper.mapValueToPathItem(spaceId))"
        let spaceIdPostEscape = spaceIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{spaceId}", with: spaceIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = PublicApiAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: createJourneyAlphaInput)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateJourney200Response>.Type = PublicApiAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }
}
